# local makefile, where the sources are.

# remember to adjust the following variables.

# where the root dir is
TOP_DIR		=../../..
#where the classes are put under the class dir (required for "make clean")
PACKAGE_DIR	=Kirrkirr/ui/dialog

include $(TOP_DIR)/Makefile.include

